public class FrontendPage {

    public static final String HTML = "<!doctype html>\n"
            + "<html lang='zh-CN'>\n"
            + "<head>\n"
            + "  <meta charset='UTF-8' />\n"
            + "  <meta name='viewport' content='width=device-width, initial-scale=1.0' />\n"
            + "  <title>策略模式 Demo</title>\n"
            + "  <style>\n"
            + "    body { font-family: 'Segoe UI', sans-serif; background: #f5f7fb; color: #1f2937; }\n"
            + "    .card { max-width: 560px; margin: 40px auto; background: #fff; border-radius: 12px; padding: 24px; box-shadow: 0 8px 20px rgba(0,0,0,.08); }\n"
            + "    h1 { margin-top: 0; font-size: 22px; }\n"
            + "    .row { margin-bottom: 12px; display: flex; gap: 8px; align-items: center; }\n"
            + "    label { width: 110px; }\n"
            + "    input, select { flex: 1; padding: 8px; border: 1px solid #d1d5db; border-radius: 8px; }\n"
            + "    button { width: 100%; margin-top: 8px; padding: 10px; border: 0; border-radius: 8px; background: #2563eb; color: #fff; cursor: pointer; }\n"
            + "    pre { background: #0f172a; color: #cbd5e1; padding: 12px; border-radius: 8px; overflow: auto; }\n"
            + "  </style>\n"
            + "</head>\n"
            + "<body>\n"
            + "  <div class='card'>\n"
            + "    <h1>策略模式 - 订单折扣计算</h1>\n"
            + "    <div class='row'>\n"
            + "      <label>单价</label>\n"
            + "      <input id='unitPrice' type='number' value='100' min='1' />\n"
            + "    </div>\n"
            + "    <div class='row'>\n"
            + "      <label>数量</label>\n"
            + "      <input id='quantity' type='number' value='2' min='1' />\n"
            + "    </div>\n"
            + "    <div class='row'>\n"
            + "      <label>策略</label>\n"
            + "      <select id='strategy'>\n"
            + "        <option value='normal'>原价</option>\n"
            + "        <option value='vip'>VIP 九折</option>\n"
            + "        <option value='new-user'>新用户减 20</option>\n"
            + "      </select>\n"
            + "    </div>\n"
            + "    <button id='calcBtn'>计算总价</button>\n"
            + "    <p>返回结果：</p>\n"
            + "    <pre id='result'>{}</pre>\n"
            + "  </div>\n"
            + "\n"
            + "  <script>\n"
            + "    const resultEl = document.getElementById('result');\n"
            + "    document.getElementById('calcBtn').addEventListener('click', async () => {\n"
            + "      const unitPrice = document.getElementById('unitPrice').value;\n"
            + "      const quantity = document.getElementById('quantity').value;\n"
            + "      const strategy = document.getElementById('strategy').value;\n"
            + "      const url = `/api/quote?unitPrice=${encodeURIComponent(unitPrice)}&quantity=${encodeURIComponent(quantity)}&strategy=${encodeURIComponent(strategy)}`;\n"
            + "      const resp = await fetch(url);\n"
            + "      const data = await resp.json();\n"
            + "      resultEl.textContent = JSON.stringify(data, null, 2);\n"
            + "    });\n"
            + "  </script>\n"
            + "</body>\n"
            + "</html>";
}
