public class TemplateFrontendPage {

    public static final String HTML = "<!doctype html>\n"
            + "<html lang='zh-CN'>\n"
            + "<head>\n"
            + "  <meta charset='UTF-8' />\n"
            + "  <meta name='viewport' content='width=device-width, initial-scale=1.0' />\n"
            + "  <title>模板方法模式 Demo</title>\n"
            + "  <style>\n"
            + "    body { font-family: 'Segoe UI', sans-serif; background: #f5f7fb; color: #1f2937; margin: 0; }\n"
            + "    .nav { background: #1e293b; padding: 12px 24px; display: flex; gap: 20px; align-items: center; }\n"
            + "    .nav a { color: #94a3b8; text-decoration: none; font-size: 14px; padding: 4px 8px; border-radius: 6px; }\n"
            + "    .nav a.active { color: #fff; background: #7c3aed; }\n"
            + "    .nav a:hover:not(.active) { color: #e2e8f0; }\n"
            + "    .card { max-width: 700px; margin: 32px auto; background: #fff; border-radius: 12px; padding: 28px; box-shadow: 0 8px 20px rgba(0,0,0,.08); }\n"
            + "    h1 { margin-top: 0; font-size: 22px; }\n"
            + "    .row { margin-bottom: 14px; display: flex; gap: 10px; align-items: center; }\n"
            + "    label { width: 90px; font-size: 14px; }\n"
            + "    select { flex: 1; padding: 8px 10px; border: 1px solid #d1d5db; border-radius: 8px; font-size: 14px; }\n"
            + "    button { width: 100%; margin-top: 6px; padding: 11px; border: 0; border-radius: 8px; background: #7c3aed; color: #fff; cursor: pointer; font-size: 15px; font-weight: 500; }\n"
            + "    button:hover { background: #6d28d9; }\n"
            + "    .section-label { margin: 20px 0 8px; font-size: 12px; font-weight: 600; color: #6b7280; text-transform: uppercase; letter-spacing: .6px; }\n"
            + "    .meta { font-size: 13px; color: #4b5563; margin-bottom: 10px; }\n"
            + "    .meta span { font-weight: 600; color: #7c3aed; }\n"
            + "    .steps { display: flex; flex-direction: column; gap: 4px; }\n"
            + "    .step { padding: 7px 12px; border-left: 3px solid #7c3aed; background: #f5f3ff; border-radius: 0 6px 6px 0; font-size: 13px; font-family: 'Consolas', monospace; }\n"
            + "    pre { background: #0f172a; color: #cbd5e1; padding: 14px; border-radius: 8px; overflow: auto; font-size: 13px; max-height: 320px; margin: 0; }\n"
            + "    #result { display: none; }\n"
            + "  </style>\n"
            + "</head>\n"
            + "<body>\n"
            + "  <div class='nav'>\n"
            + "    <a href='/'>策略模式</a>\n"
            + "    <a href='/template' class='active'>模板方法</a>\n"
            + "    <a href='/simple-factory'>简单工厂</a>\n"
            + "    <a href='/factory-method'>工厂方法</a>\n"
            + "    <a href='/abstract-factory'>抽象工厂</a>\n"
            + "    <a href='/chain'>责任链</a>\n"
            + "  </div>\n"
            + "  <div class='card'>\n"
            + "    <h1>模板方法模式 — 报表导出</h1>\n"
            + "    <div class='row'>\n"
            + "      <label>导出格式</label>\n"
            + "      <select id='format'>\n"
            + "        <option value='json'>JSON</option>\n"
            + "        <option value='csv'>CSV</option>\n"
            + "        <option value='csv-big'>CSV（仅大额订单 — 钩子方法演示）</option>\n"
            + "        <option value='xml'>XML</option>\n"
            + "      </select>\n"
            + "    </div>\n"
            + "    <button id='exportBtn'>导出报表</button>\n"
            + "\n"
            + "    <div id='result'>\n"
            + "      <div class='section-label'>执行类</div>\n"
            + "      <p class='meta'>调用链路：<span>ReportExporter.export()</span> → <span id='exporterClass'></span></p>\n"
            + "      <div class='section-label'>模板方法执行步骤</div>\n"
            + "      <div id='steps' class='steps'></div>\n"
            + "      <div class='section-label'>导出结果</div>\n"
            + "      <pre id='output'></pre>\n"
            + "    </div>\n"
            + "  </div>\n"
            + "\n"
            + "  <script>\n"
            + "    document.getElementById('exportBtn').addEventListener('click', async () => {\n"
            + "      const format = document.getElementById('format').value;\n"
            + "      const resp = await fetch(`/api/export?format=${format}`);\n"
            + "      const data = await resp.json();\n"
            + "      document.getElementById('exporterClass').textContent = data.exporterClass;\n"
            + "      document.getElementById('steps').innerHTML =\n"
            + "        data.steps.map(s => `<div class='step'>${s}</div>`).join('');\n"
            + "      document.getElementById('output').textContent = data.output;\n"
            + "      document.getElementById('result').style.display = 'block';\n"
            + "    });\n"
            + "  </script>\n"
            + "</body>\n"
            + "</html>";
}
